# stack with only ec2 instance

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      SubnetId: 'subnet-09c627ce914a28786'
      SecurityGroupIds:
      - !Ref MySecurityGroup
      UserData:
      #use aws s3 cp s3://bucketname/filename /path/to/file to get files from s3 and not github for csv later
      #add credential section for github
      #need secrets manager
      #IAM roles for EC2 instance secret manager
      #IAM roles for EC2 instance S3
      #IAM roles for S3 to grab from EC2 instance
      #add statement to prevent delete of S3 bucket
      #cloudwatch logs if error
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y aws-cfn-bootstrap
          yum install awscli -y
          wget https://github.com/kpancha1/POC-test-file-R/blob/main/testfile.R
          inputFile=$(aws s3 cp s3://Input-S3-Bucket-POC2023/testfile.R -)
          if [[ -n "$inputFile" ]]; then
            echo "File content:" > worked.txt
            echo "$inputFile" >> worked.txt
            aws s3 cp worked.txt s3://Output-S3-Bucket-POC2023/
          else
            echo "Failed to retrieve file content." > error.txt
            aws s3 cp error.txt s3://Output-S3-Bucket-POC2023/
          fi

         
      InstanceType: m1.small
      AvailabilityZone: us-east-1a
      ImageId: ami-0ff8a91507f77f867


      #  wget https://github.com/dconroybeam/CSM-Match/blob/e69c72947a5d55c09dd5dc9be6a802712831f3c6/Mock%20Data/CSM%20Match%20Mock%20Data%2020230720%20164351.csv
      #     wget https://github.com/dconroybeam/CSM-Match/blob/e69c72947a5d55c09dd5dc9be6a802712831f3c6/Mock%20Data/CSM%20Match%20Mock%20Matching%20Script%2020230720.Rmd
      #     Rscript CSM%20Match%20Mock%20Matching%20Script%2020230720.Rmd CSM%20Match%20Mock%20Data%2020230720%20164351.csv
      #     current_date=$(date +"%Y.%m.%d")
      #     current_time=$(date +"%H.%M.%S")
      #     file_name_base="CSM MATCH Mock Data MATCHED"
      #     file_name="${file_name_base}_${current_date}_${current_time}.csv"
      #     if [[ ! -e "$file_name" ]]; then
      #       echo "error" > error.txt
      #       aws s3 cp error.txt s3://csm-match-mock-data-matched/
      #     else
      #       aws s3 cp "$file_name" s3://csm-match-mock-data-matched/
      #     fi