# following commands that local computer will have to run (in order)
#1. Command to create stack:
# aws cloudformation create-stack --stack-name NewStackName --template-body file://path/to/your/existing-template.yaml --region us-west-2
# 2. Command that will upload local csv file onto existing s3 bucket
# aws s3 cp /path/to/your/csvfile.csv s3://your-existing-bucket-name/csvfile.csv

# local computer will need credentials to run above

# template plans:
# 1. contains services that will run once and will stay; includes: output s3 bucket, security group, iam roles, input bucket
# 2. contains services that will run everytime; includes: ec2 instance

# to-do:
#EC2 launch role
#add a security group
#vpc and subnet id
#service catalog vpc
#multiple parameters
#parameters use default or json file in CLI

Resources:
# bucket policies and iam roles
  InputS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Input-S3-Bucket-POC2023
      Statement:
        Action: s3:GetObject
        Effect: Allow
        Resource: !Sub arn:aws:s3:::${Input-S3-Bucket-POC2023}/*
        Principal:
          Service: ec2.amazonaws.com

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2InstanceRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EC2S3AccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource:
                  - !Sub arn:aws:s3:::${Input-S3-Bucket-POC2023}/*
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub arn:aws:s3:::${Output-S3-Bucket-POC2023}/*

  OutputS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref Output-S3-Bucket-POC2023
        Statement:
          Action: s3:PutObject
          Effect: Allow
          Resource: !Sub arn:aws:s3:::${Output-S3-Bucket-POC2023}/*
          Principal:
            Service: ec2.amazonaws.com
  
# s3 buckets (input and output)
  Input-S3-Bucket-POC2023:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: csm-match-mock-data
    DeletionPolicy: Delete
    Region: us-west-2

  Output-S3-Bucket-POC2023:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: csm-match-mock-data-matched
    DeletionPolicy: Retain
    Region: us-west-2

  MyLifecycleConfiguration:
    Type: AWS::S3::BucketLifecycleConfiguration
    Properties:
      Bucket: !Ref Output-S3-Bucket-POC2023
      LifecycleConfiguration:
        Rules:
          - Id: Retain3Days
            Status: Enabled
            ExpirationInDays: 3

  # based on how many times we think the instance will have to run per quarter
  # option 1: to have instance terminate each time so bash runs everytime
  # option 2: find a way for instance to re-run userdata bash script w/o termination
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My EC2 instance security group
      VpcId: 'vpc-00b9bd3a6d70475f1'
      # security group still needs to be completed!!