# following commands that local computer will have to run (in order)
#1. Command to create stack:
# aws cloudformation create-stack --stack-name NewStackName --template-body file://path/to/your/existing-template.yaml --region us-west-2
# 2. Command that will upload local csv file onto existing s3 bucket
# aws s3 cp /path/to/your/csvfile.csv s3://your-existing-bucket-name/csvfile.csv

# local computer will need credentials to run above

# template plans:
# 1. contains services that will run once and will stay; includes: output s3 bucket, security group, iam roles, input bucket
# 2. contains services that will run everytime; includes: ec2 instance

# to-do:
#EC2 launch role
#add a security group
#vpc and subnet id
#service catalog vpc
#multiple parameters
#parameters use default or json file in CLI

Resources:
  # Bucket policies and IAM roles
  InputS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref InputS3BucketPOC2023
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${InputS3BucketPOC2023}/*
            Principal:
              Service: ec2.amazonaws.com

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2InstanceRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EC2S3AccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource:
                  - !Sub arn:aws:s3:::${InputS3BucketPOC2023}/*
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub arn:aws:s3:::${OutputS3BucketPOC2023}/*

  OutputS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OutputS3BucketPOC2023
      PolicyDocument:
        Statement:
          - Action: s3:PutObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${OutputS3BucketPOC2023}/*
            Principal:
              Service: ec2.amazonaws.com

  # S3 buckets (input and output)
  InputS3BucketPOC2023:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: csm-match-mock-data
    DeletionPolicy: Delete

  OutputS3BucketPOC2023:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: csm-match-mock-data-matched
      LifecycleConfiguration:
        Rules:
          - Id: Retain3Days
            Status: Enabled
            ExpirationInDays: 3
    DeletionPolicy: Retain